Repository contao-community-alliance/dc-general, pull requests merged in 2018-03, with the labels that each got.

#359 [RTM] Feature override/edit all
  composer.json
  contao/config/event_listeners.php
  contao/config/event_subscribers.php
  contao/config/services.php
  contao/html/css/generalDriver.css
  contao/html/images/loading.gif
  contao/html/js/generalDriver_src.js
  contao/html/sass/_messageBox.scss
  contao/html/sass/generalDriver.scss
  contao/languages/de/default.php
  contao/languages/en/default.php
  contao/templates/dcbe_general_common_list.html5
  contao/templates/dcbe_general_edit.html5
  contao/templates/dcbe_general_treeview_entry.html5
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/AbstractListShowAllHandler.php
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/CopyHandler.php
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/DeleteHandler.php
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/EditAllHandler.php
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/EditHandler.php
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/ListViewShowAllPropertiesHandler.php
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/OverrideAllHandler.php
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/ParentedListViewShowAllHandler.php
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/PasteAllHandler.php
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/PasteHandler.php
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/SelectHandler.php
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoBackendViewTemplate.php
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Controller/ClipboardController.php
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EventListener/BackButtonListener.php
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/PanelRenderer.php
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Subscriber/EditAllHandlerSubscriber.php
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php
  src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php
  src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php
  src/ContaoCommunityAlliance/DcGeneral/Data/DataProviderInterface.php
  src/ContaoCommunityAlliance/DcGeneral/Data/DefaultDataProvider.php
  src/ContaoCommunityAlliance/DcGeneral/Data/DefaultEditInformation.php
  src/ContaoCommunityAlliance/DcGeneral/Data/EditInformationInterface.php
  src/ContaoCommunityAlliance/DcGeneral/Data/NoOpDataProvider.php
  src/ContaoCommunityAlliance/DcGeneral/Data/TableRowsAsRecordsDataProvider.php
  src/ContaoCommunityAlliance/DcGeneral/View/ActionHandler/AbstractPropertyOverrideEditAllHandler.php
  src/ContaoCommunityAlliance/DcGeneral/View/ActionHandler/AbstractPropertyVisibilityHandler.php
Labels: bug, enhancement

#399 [RTM] Hotfix add HTML class at buttons
  src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ButtonRenderer.php
Labels: enhancement

#402 [RTM] Hotfix reset fallback PR #321
  src/ContaoCommunityAlliance/DcGeneral/Contao/Subscriber/FallbackResetSubscriber.php
Labels: bug
