Repository contao-community-alliance/dc-general, pull requests merged in 2023-11, with the labels that each got.

#613 Fix undefined array key problem
  src/Contao/Subscriber/FormatModelLabelSubscriber.php
Labels: bug, PHP 8

#614 Fix limit of list
  src/Panel/DefaultLimitElement.php
Labels: bug

#615 Fix request token at change language
  src/Contao/Dca/Populator/BackendViewPopulator.php
  src/Contao/View/Contao2BackendView/ActionHandler/AbstractListShowAllHandler.php
  src/Contao/View/Contao2BackendView/ActionHandler/ShowHandler.php
  src/Contao/View/Contao2BackendView/TreeView.php
  src/Resources/config/contao/handler_backend_listeners.yml
  src/Resources/config/contao/handler_multiple_backend_listeners.yml
  src/Resources/config/services.yml
  src/Resources/contao/templates/dcbe_general_common_list.html5
  src/Resources/contao/templates/dcbe_general_edit.html5
  src/Resources/contao/templates/dcbe_general_language_panel.html5
  src/Resources/contao/templates/dcbe_general_panel.html5
  src/Resources/contao/templates/dcbe_general_treeview.html5
  src/Resources/contao/templates/widget_common_picker.html5
  src/Resources/contao/templates/widget_filetree.html5
Labels: bug

#616 Add grouping by week (replaces #533)
  src/Contao/View/Contao2BackendView/Subscriber/GetGroupHeaderSubscriber.php
  src/Resources/contao/languages/de/default.php
  src/Resources/contao/languages/en/default.php
Labels: enhancement

#619 Fix code style in templates
  src/Resources/contao/templates/dc_general_wizard_common_picker.html5
  src/Resources/contao/templates/dcbe_general_clipboard.html5
  src/Resources/contao/templates/dcbe_general_field.html5
  src/Resources/contao/templates/dcbe_general_panel_filter.html5
  src/Resources/contao/templates/dcbe_general_panel_limit.html5
  src/Resources/contao/templates/dcbe_general_panel_sort.html5
  src/Resources/contao/templates/dcbe_general_panel_submit.html5
  src/Resources/contao/templates/dcbe_general_show.html5
  src/Resources/contao/templates/dcbe_general_treeview_child.html5
  src/Resources/contao/templates/dcbe_general_treeview_entry.html5
  src/Resources/contao/templates/widget_treepicker.html5
  src/Resources/contao/templates/widget_treepicker_child.html5
  src/Resources/contao/templates/widget_treepicker_entry.html5
  src/Resources/contao/templates/widget_treepicker_popup.html5
Labels: enhancement

#618 Fix issue 617
  src/Contao/Callback/Callbacks.php
Labels: bug

#622 Fix rebase from pr 608
  src/Contao/Callback/Callbacks.php
  src/Contao/Compatibility/DcCompat.php
  src/Contao/Dca/Builder/Legacy/LegacyDcaDataDefinitionBuilder.php
  src/Contao/View/Contao2BackendView/ActionHandler/MultipleHandler/OverrideAllHandler.php
  src/Contao/View/Contao2BackendView/EditMask.php
  src/Contao/View/Contao2BackendView/Widget/AbstractWidget.php
  src/DC/General.php
  src/DataContainerInterface.php
  src/Panel/DefaultLimitElement.php
Labels: enhancement
